CREATE TABLE `notification` (
  `ID` bigint(20) NOT NULL,
  `FL_READ` tinyint(1) DEFAULT NULL,
  `TYPE` bigint(20) DEFAULT NULL,
  `TASK_ID` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `notification_type` (
  `ID` bigint(20) NOT NULL,
  `TYPE` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `notification`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `FK_NOTIFICATION_TYPE_NOTIFICATION` (`TYPE`),
  ADD KEY `FK_TASK_NOTIFICATION` (`TASK_ID`);
  
  ALTER TABLE `notification_type`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `TYPE` (`TYPE`);
  
  ALTER TABLE `notification`
  ADD CONSTRAINT `FK_NOTIFICATION_TYPE_NOTIFICATION` FOREIGN KEY (`TYPE`) REFERENCES `notification_type` (`ID`),
  ADD CONSTRAINT `FK_TASK_NOTIFICATION` FOREIGN KEY (`TASK_ID`) REFERENCES `task` (`ID`);